### ISSUE TITLE
Trigger button won't close options unless search box is present

### ISSUE THREAD

**Issue by iboxifoo** [dahliacreative/selectron#20]
Thanks for selectron, well thought out.

I noticed unless you set `search: true` in selectron's options, the trigger button won't close an open options list. Possibly a DOM traversal issue?

**Comment by dahliacreative** [comment]
Hi, sorry for the extremely late reply! Been so busy at work I haven't checked up in a while.

Can you check if this is still happening? I think I may have fixed it. If it's still happening can you paste a link to a demo as I can't seem to replicate it.

Thanks

**Comment by iboxifoo** [comment]
Np @dahliacreative. The project I was using Selectron on has moved on so not really in a position to test right now. But I'll let you know if I am able to test your fix. I take it it's in the recent commit?

**Comment by dahliacreative** [comment]
Not sure tbh, I think I may have fixed it in an earlier commit without realising. What version were you using?

**Comment by dahliacreative** [comment]
Closing this as latest version seems to work.
